"""
Merge migrations

Revision ID: 003_merge_migrations
Revises: 9a027d5ad82b, 002_add_snowflake_connections
Create Date: 2025-05-15 12:20:00.000000
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003_merge_migrations'
down_revision = ('9a027d5ad82b', '002_add_snowflake_connections')
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
